return {}
--    "yetone/avante.nvim",
--    event = "VeryLazy",
--    version = false, -- Never set this value to "*"! Never!
--    ---@module 'avante'
--    ---@type avante.Config
--    opts = {
--        provider = "ollama",
--        providers = {
--            ollama = {
--                model = "gpt-oss:20b",
--                is_env_set = function()
--                    return require("avante.providers.ollama").check_endpoint_alive()
--                end
--            }
--        }
--    },
--    dependencies = {q
--        "nvim-lua/plenary.nvim",
--        "MunifTanjim/nui.nvim",
--        --- The below dependencies are optional,
--        "hrsh7th/nvim-cmp",            -- autocompletion for avante commands and mentions
--        "ibhagwan/fzf-lua",            -- for file_selector provider fzf
--        "stevearc/dressing.nvim",      -- for input provider dressing
--        "folke/snacks.nvim",           -- for input provider snacks
--        "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--        {
--            -- support for image pasting
--            "HakonHarnes/img-clip.nvim",
--            event = "VeryLazy",
--            opts = {
--                -- recommended settings
--                default = {
--                    embed_image_as_base64 = false,
--                    prompt_for_file_name = false,
--                    drag_and_drop = {
--                        insert_mode = true,
--                    },
--                    -- required for Windows users
--                    use_absolute_path = true,
--                },
--            },
--        },
--        {
--            -- Make sure to set this up properly if you have lazy=true
--            'MeanderingProgrammer/render-markdown.nvim',
--            opts = {
--                file_types = { "markdown", "Avante" },
--            },
--            ft = { "markdown", "Avante" },
--        },
--    },
--}
