set-option -g default-shell $SHELL

set -as terminal-features ',xterm-256color'
set -g default-terminal "xterm-256color"

set -g display-time 150
set -g base-index 1
set -g mouse on

set -g status-style bg=colour0,fg=colour223
set -g status-left-length 50
set -g status-left ' #{?#{e|>:#{n:session_name},20},#{=17:session_name}...,#{session_name}} | '
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"
set -g window-status-current-style 'fg=colour136,bold'

set-hook -g session-created 'run-shell "tmux send-keys -t #{session_name} \"tmux_init\" C-m"'

bind r source-file ~/.tmux.conf \; display "Reloaded config"
bind -n C-f display-popup -E "tms"
